### ISSUE TITLE
Some questions about assignment-2

### ISSUE THREAD

**Issue by Nicholas-wei** [SVF-tools/Teaching-Software-Analysis#41]
Hello dear author:
I really appreciate your SVF tool and the course you have provided. Thank you very much!
I have encountered some problems in assignment-2, I have followed your pseudocode in your PPT and unfortunately, the `iter` object in the picture below(type of ICFGEdge) is unable to be converted to `CallCFGEdge` type, so I can't get the instruction object by using `getCallSite()` function. The red lines below the code show the error part.
I have beed bothered with this problem for days. Can you offere me some advice?Thank you.

![图片](https://user-images.githubusercontent.com/63231742/193594722-95d448ee-88c2-4854-bc3b-a73e47fb4bd8.png)

**Comment by tompansir** [comment]
I had the same problem last semester. But the teacher explained in the tutorial that this thing is transformed. The attachment may help you.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SVF-tools/Teaching-Software-Analysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月3日(星期一) 晚上10:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[SVF-tools/Teaching-Software-Analysis] Some questions about assignment-2 (Issue #41)





 
Hello dear author:
 I really appreciate your SVF tool and the course you have provided. Thank you very much!
 I have encountered some problems in assignment-2, I have followed your pseudocode in your PPT and unfortunately, the iter object in the picture below(type of ICFGEdge) is unable to be converted to CallCFGEdge type, so I can't get the instruction object by using getCallSite() function. The red lines below the code show the error part.
 I have beed bothered with this problem for days. Can you offere me some advice?Thank you.

**Comment by Nicholas-wei** [comment]
> 

thanks for your reply :). But I can't find the attachments, can you re-upload it, thanks!

**Comment by tompansir** [comment]
I am a student of Northeastern University of China. Because of the cooperation between my university and UTS, I was lucky to participate in this course last semester. If the code for this semester's assignment has not changed, you can refer to the code I wrote last semester.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SVF-tools/Teaching-Software-Analysis"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年10月3日(星期一) 晚上10:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SVF-tools/Teaching-Software-Analysis] Some questions about assignment-2 (Issue #41)





   
thanks for your reply :). But I can't find the attachments, can you re-upload it, thanks!

**Comment by Nicholas-wei** [comment]
> 

Thank you! But it seems that you didn't make the code public on your github(which is supposed to be :)). Can you share your code link or code attachment  with me by sending an e-mail to 19307130034@fudan.edu.cn? Thank you very much! And sorry for bothering you so much time.

**Comment by Nicholas-wei** [comment]
Thank You!

**Comment by xuanzhiliu** [comment]
I faced the same problem, how do you solve it ?
